const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'chatgpt-conversation-handoff-exporter.user.js'), 'utf8');
const bridge = fs.readFileSync(path.join(root, 'continuity-storage-bridge.js'), 'utf8');
const readme = fs.readFileSync(path.join(root, 'README.md'), 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8').replace(/^\uFEFF/, ''));

assert.match(source, /@version\s+1\.4\.0/);
assert.equal(manifest.version, '1.4.0');
assert.deepEqual(manifest.permissions, ['storage']);
assert.equal(manifest.content_scripts[0].world, 'ISOLATED');
assert.equal(manifest.content_scripts[0].js[0], 'continuity-storage-bridge.js');
assert.equal(manifest.content_scripts[1].world, 'MAIN');
assert.match(source, /UAIOS_CONTINUITY_VERSION = '1\.4\.0'/);
assert.match(source, /uaiosContinuityBridgeRequest/);
assert.match(source, /savePending/);
assert.match(source, /getPending/);
assert.match(source, /clearPending/);
assert.match(bridge, /chrome\.storage\.local/);
assert.match(bridge, /bridge_redirect_attempts/);
assert.match(bridge, /location\.replace\(record\.project_href\)/);
assert.match(source, /UAIOS_AUTO_CHECKPOINT_MS = 10 \* 60 \* 1000/);
assert.match(source, /New Chat Handoff/);
assert.match(source, /uaiosContinuityPrepareRollover/);
assert.match(source, /uaiosContinuityApplyPendingRollover/);
assert.ok(source.includes('const projectLandingRoute = path.match(/^(\\/g\\/g-p-[^/]+)\\/project(?:\\/.*)?$/i);'));
assert.ok(source.includes('return new URL(`${scope}/project`, location.origin).href;'));
assert.match(source, /project_href: projectHref/);
assert.match(source, /total_content_chars/);
assert.match(readme, /heuristic conversation load/i);
assert.match(readme, /not an OpenAI token meter/i);

const applyStart = source.indexOf('async function uaiosContinuityApplyPendingRollover');
const applyEnd = source.indexOf('async function uaiosContinuityPrepareRollover', applyStart);
const applyBody = source.slice(applyStart, applyEnd);
assert.ok(applyStart > 0 && applyEnd > applyStart);
assert.doesNotMatch(applyBody, /\.click\(|requestSubmit\(|dispatchEvent\([^)]*submit/i, 'resume must never auto-send');
console.log('v1.4.0 continuity static tests: PASS');
