const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'chatgpt-conversation-handoff-exporter.user.js'), 'utf8');
const bridge = fs.readFileSync(path.join(root, 'continuity-storage-bridge.js'), 'utf8');
const background = fs.readFileSync(path.join(root, 'background.js'), 'utf8');
const readme = fs.readFileSync(path.join(root, 'README.md'), 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8').replace(/^\uFEFF/, ''));

assert.match(source, /@version\s+1\.6\.4/);
assert.equal(manifest.version, '1.6.4');
assert.deepEqual(manifest.permissions, ['storage', 'tabs']);
assert.equal(manifest.background.service_worker, 'background.js');
assert.equal(manifest.content_scripts[0].world, 'ISOLATED');
assert.equal(manifest.content_scripts[0].js[0], 'continuity-storage-bridge.js');
assert.equal(manifest.content_scripts[1].world, 'MAIN');
assert.match(source, /UAIOS_CONTINUITY_VERSION = '1\.6\.4'/);
assert.match(source, /UAIOS_BRIDGE_REQUEST_MAILBOX_ID/);
assert.match(source, /Bridge: /);
assert.match(source, /openHandoffTab/);
assert.match(source, /uaiosContinuityBridgeRequest/);
assert.match(bridge, /chrome\.storage\.local/);
assert.match(bridge, /chrome\.runtime\.sendMessage/);
assert.match(bridge, /uaios-open-handoff-tab/);
assert.match(bridge, /REQUEST_MAILBOX_ID/);
assert.match(bridge, /REPLY_MAILBOX_ID/);
assert.match(source, /new MutationObserver\(onReply\)/);
assert.match(bridge, /new MutationObserver\(processMailbox\)/);
assert.doesNotMatch(bridge, /event\.source !== window/, 'bridge must not compare Window wrappers across execution worlds');
assert.match(background, /chrome\.tabs\.create/);
assert.match(background, /chrome\.tabs\.onUpdated/);
assert.match(background, /chrome\.tabs\.update/);
assert.match(background, /recovery_attempts/);
assert.match(source, /UAIOS_AUTO_CHECKPOINT_MS = 10 \* 60 \* 1000/);
assert.match(source, /New Chat Handoff/);
assert.match(source, /EXPORT_HEADER_BUTTONS_ENABLED = false/);
assert.match(source, /Advanced \/ Export/);
assert.match(source, /Download Raw JSON/);
assert.match(source, /Download Handoff JSON/);
assert.match(source, /data-uaios-more/);
assert.match(source, /data-uaios-action="export-raw"/);
assert.match(source, /data-uaios-action="export-handoff"/);
assert.match(source, /uaiosContinuityPrepareRollover/);
assert.match(source, /uaiosContinuityApplyPendingRollover/);
assert.match(source, /uaiosContinuityStageRollover/);
assert.match(source, /handoff_state: 'staged'/);
assert.match(source, /handoff_state: 'ready'/);
assert.match(source, /window\.open\(stagedRecord\.project_href, '_blank'\)/);
assert.match(source, /uaiosContinuityPrepareRollover\(preopenedTab = null, stagedRecord = null\)/);
assert.match(source, /UAIOS_STAGED_HANDOFF_WAIT_MS = 4000/);
assert.match(source, /async function uaiosContinuityFillComposer/);
assert.match(source, /uaiosContinuityComposerText/);
assert.match(source, /document\.execCommand\?\.\('insertText'/);
assert.match(source, /rollover_bootstrap_fill_failed/);
assert.match(source, /pending = uaiosContinuitySetPendingRollover\(bridged\)/);
assert.match(source, /Composer hydration failed; pending handoff kept/);
assert.match(source, /for \(const delay of \[180, 650, 1400\]\)/);
assert.match(source, /for \(let attempt = 0; attempt < 2; attempt \+= 1\)/);
assert.match(source, /new InputEvent\('beforeinput'/);
assert.match(source, /ChatGPT\/React can briefly accept a DOM write/);
assert.match(source, /function uaiosContinuityIsVisibleComposer/);
assert.match(source, /element\.id === 'prompt-textarea'/);
assert.match(source, /rect\.width >= 120 && rect\.height >= 20/);
assert.match(source, /filter\(\(element\) => uaiosContinuityIsVisibleComposer\(element\)\)/);
assert.match(source, /if \(!current \|\| !uaiosContinuityIsVisibleComposer\(current\)\) return false/);
assert.doesNotMatch(source, /preopenedTab\.location\.replace\(targetUrl\)/, 'direct Project tab must not bounce through about:blank');
assert.ok(source.includes("const projectRoute = path.match(/^\\/g\\/(g-p-[0-9a-f]+)(?:-[^/]+)?(?:\\/|$)/i);"));
const projectRoutePattern = /^\/g\/(g-p-[0-9a-f]+)(?:-[^/]+)?(?:\/|$)/i;
const projectRoute = '/g/g-p-0123456789abcdef0123456789abcdef-conversation-continuity-protocol/c/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'.match(projectRoutePattern);
assert.equal(`/g/${projectRoute[1]}`, '/g/g-p-0123456789abcdef0123456789abcdef');
assert.ok(source.includes('const projectLandingRoute = path.match(/^(\\/g\\/g-p-[^/]+)\\/project(?:\\/.*)?$/i);'));
assert.match(source, /project_href: projectHref/);
assert.match(source, /total_content_chars/);
assert.match(source, /If project_state is missing or stale, reconstruct a provisional project state from recent_messages before continuing\./);
assert.match(source, /function uaiosContinuityDeriveProjectState/);
assert.match(source, /function uaiosContinuityMergeProjectState/);
assert.match(source, /function uaiosContinuityFormatProjectState/);
assert.match(source, /state_source: 'autopilot-v1'/);
assert.match(source, /project_state_schema_version: 1/);
assert.match(source, /PROJECT STATE SNAPSHOT/);
assert.match(source, /data-uaios-state="wait"/);
assert.match(source, /UAIOS_CONTINUITY_PANEL_POSITION_KEY/);
assert.match(source, /data-uaios-drag-handle/);
assert.match(source, /lastHandleClickAt/);
assert.match(source, /now - lastHandleClickAt <= 450/);
assert.match(source, /Math\.hypot\(event\.clientX - lastHandleClickPoint\.x/);
assert.match(source, /uaiosContinuityResetPanelPosition\(panel\)/);
assert.match(source, /pointerdown/);
const dragStart = source.indexOf("handle.addEventListener('pointerdown'");
const dragMove = source.indexOf("handle.addEventListener('pointermove'", dragStart);
const dragStartBody = source.slice(dragStart, dragMove);
assert.ok(dragStart > 0 && dragMove > dragStart);
assert.doesNotMatch(dragStartBody, /preventDefault\(\)/, 'pointerdown must preserve compatibility mouse events');
assert.match(source, /double-click to reset/);
assert.match(source, /deriveState:/);
assert.match(source, /Do not ask the user to repeat context already present in this bootstrap\. Continue when the next action is clear\./);
assert.match(readme, /heuristic conversation load/i);
assert.match(readme, /not an OpenAI token meter/i);
const applyStart = source.indexOf('async function uaiosContinuityApplyPendingRollover');
const applyEnd = source.indexOf('async function uaiosContinuityPrepareRollover', applyStart);
const applyBody = source.slice(applyStart, applyEnd);
assert.ok(applyStart > 0 && applyEnd > applyStart);
assert.doesNotMatch(applyBody, /\.click\(|requestSubmit\(|dispatchEvent\([^)]*submit/i, 'resume must never auto-send');
assert.doesNotMatch(background, /cookies|Authorization|Bearer/i, 'background controller must not handle auth secrets');
console.log('v1.6.4 continuity static tests: PASS');